export interface SeedItem {
  text: string;
  prechecked: boolean;
}

export interface SeedCategory {
  id: string;
  emoji: string;
  label: string;
  items: SeedItem[];
}

export const seedCategories: SeedCategory[] = [
  {
    id: "maeve",
    emoji: "👶",
    label: "Maeve (18 mo)",
    items: [
      { text: "Diaper bag", prechecked: false },
      { text: "Tablet (loaded with shows)", prechecked: false },
      { text: "Diapers", prechecked: false },
      { text: "Wipes", prechecked: false },
      { text: "Overnight pads", prechecked: false },
      { text: "Disposable bibs", prechecked: false },
      { text: "Water cups × 2", prechecked: false },
      { text: "Snack cups × 2", prechecked: false },
      { text: "Snacks + pouches", prechecked: false },
      { text: "Packable blanket", prechecked: false },
      { text: "Sand toys", prechecked: false },
      { text: "Baby monitor", prechecked: false },
      { text: "Sound machine", prechecked: false },
      { text: "Pool bag", prechecked: false },
      { text: "Light jacket", prechecked: false },
      { text: "Car seat", prechecked: false },
      { text: "First aid kit", prechecked: false },
      { text: "Guava travel crib", prechecked: false },
      { text: "Sleep sack", prechecked: false },
      { text: "Miss Mouth's stain remover", prechecked: false },
      { text: "Pajamas × 4", prechecked: true },
      { text: "Swim diapers", prechecked: true },
      { text: "Motrin", prechecked: true },
      { text: "Tylenol", prechecked: true },
      { text: "Allergy meds", prechecked: true },
      { text: "Teething drops", prechecked: true },
      { text: "Day outfits × 5", prechecked: true },
      { text: "Swimsuits × 3", prechecked: true },
      { text: "Sneakers × 1", prechecked: true },
      { text: "Sandals × 2", prechecked: true },
      { text: "Sunscreen stick", prechecked: true },
      { text: "Life jacket / swim vest", prechecked: true },
      { text: "Sun hats", prechecked: true },
    ],
  },
  {
    id: "clothes-charles",
    emoji: "👔",
    label: "Charles — Clothes",
    items: [
      { text: "Swim trunks × 2-3", prechecked: false },
      { text: "Rash guard / swim shirt", prechecked: false },
      { text: "T-shirts / tanks × 4", prechecked: false },
      { text: "Shorts × 3", prechecked: false },
      { text: "Dinner outfit(s) × 2 (collared shirt + chinos)", prechecked: false },
      { text: "Underwear × 5", prechecked: false },
      { text: "Socks × 3 pairs", prechecked: false },
      { text: "Flip flops / sandals", prechecked: false },
      { text: "Water shoes (for waterpark)", prechecked: false },
      { text: "Sneakers or casual shoes", prechecked: false },
      { text: "Dress shoes or loafers (nicer dinners)", prechecked: false },
      { text: "Baseball cap / hat", prechecked: false },
      { text: "Sunglasses", prechecked: false },
    ],
  },
  {
    id: "clothes-carly",
    emoji: "👗",
    label: "Carly — Clothes",
    items: [
      { text: "Swimsuits × 2-3", prechecked: false },
      { text: "Coverup(s) × 2", prechecked: false },
      { text: "Casual daywear × 4", prechecked: false },
      { text: "Dinner outfits × 2", prechecked: false },
      { text: "Undergarments × 5", prechecked: false },
      { text: "Pajamas × 2", prechecked: false },
      { text: "Sandals / flip flops", prechecked: false },
      { text: "Walking shoes / sneakers", prechecked: false },
      { text: "Dress shoes or wedges (dinners)", prechecked: false },
      { text: "Sun hat", prechecked: false },
      { text: "Sunglasses", prechecked: false },
      { text: "Light cardigan or wrap (for AC)", prechecked: false },
    ],
  },
  {
    id: "beach-pool",
    emoji: "🏖️",
    label: "Beach & Pool",
    items: [
      { text: "Reef-safe sunscreen (adults)", prechecked: false },
      { text: "After-sun / aloe vera gel", prechecked: false },
      { text: "Waterproof phone pouch × 2", prechecked: false },
      { text: "Dry bag for valuables", prechecked: false },
      { text: "Baby float / puddle jumper", prechecked: false },
      { text: "Beach blanket", prechecked: false },
      { text: "Reusable water bottles", prechecked: false },
    ],
  },
  {
    id: "travel",
    emoji: "✈️",
    label: "Travel & Transit",
    items: [
      { text: "Passports — all 3!", prechecked: false },
      { text: "Boarding passes / airline app ready", prechecked: false },
      { text: "Hotel confirmation saved", prechecked: false },
      { text: "Gate-check bag for stroller", prechecked: false },
      { text: "Carry-on packed with Maeve essentials", prechecked: false },
      { text: "Plane snacks & entertainment for Maeve", prechecked: false },
      { text: "Headphones / AirPods", prechecked: false },
      { text: "Extra outfit in carry-on (for all 3)", prechecked: false },
      { text: "Ziploc bags (assorted sizes)", prechecked: false },
      { text: "Stroller", prechecked: false },
    ],
  },
  {
    id: "toiletries",
    emoji: "🧴",
    label: "Toiletries & Health",
    items: [
      { text: "Toothbrushes + toothpaste (adults)", prechecked: false },
      { text: "Deodorant", prechecked: false },
      { text: "Shampoo & conditioner", prechecked: false },
      { text: "Hair products / hair ties", prechecked: false },
      { text: "Razor", prechecked: false },
      { text: "Contact lenses / solution", prechecked: false },
      { text: "Prescription medications", prechecked: false },
      { text: "Ibuprofen / Tylenol (adults)", prechecked: false },
      { text: "Hand sanitizer", prechecked: false },
      { text: "Bug spray", prechecked: false },
      { text: "Baby shampoo / body wash", prechecked: false },
      { text: "Baby toothbrush + toothpaste", prechecked: false },
    ],
  },
  {
    id: "tech",
    emoji: "🔌",
    label: "Tech & Misc",
    items: [
      { text: "Phone chargers × 2", prechecked: false },
      { text: "Portable battery pack", prechecked: false },
      { text: "Camera / GoPro (waterpark!)", prechecked: false },
      { text: "iPad charger / tablet charger", prechecked: false },
      { text: "Kid headphones (for plane)", prechecked: false },
      { text: "Power strip / multi-outlet", prechecked: false },
      { text: "Cash + credit cards", prechecked: false },
      { text: "Travel insurance docs", prechecked: false },
    ],
  },
];
