export interface EventLocation {
  name: string;
  address?: string;
  query?: string;
  lat?: number;
  lng?: number;
}

export interface ScheduleEvent {
  id: string;
  dayNumber: number;
  date: string;
  time: string; // HH:MM 24h Europe/Madrid
  endTime?: string;
  title: string;
  description: string;
  tip?: string;
  location?: EventLocation;
  type: "travel" | "dining" | "wine" | "culture" | "activity" | "hotel" | "sport" | "free";
  highlight?: boolean;
  durationMinutes?: number;
  confirmation?: string;
  splitGroup?: "guys" | "girls"; // for Day 2 split events
}

export interface TripDay {
  dayNumber: number;
  date: string;
  weekday: string;
  title: string;
  city: string;
  emoji: string;
  summary: string;
  events: ScheduleEvent[];
}

export const tripDays: TripDay[] = [
  // ===== DAY 1 — Sat May 16 — Arrive Madrid =====
  {
    dayNumber: 1,
    date: "2026-05-16",
    weekday: "Saturday",
    title: "Arrive Madrid",
    city: "Madrid",
    emoji: "✈️",
    summary: "Land early, check in, and ease into Madrid with a market lunch, Retiro Park, and an epic tapas crawl through La Latina.",
    events: [
      {
        id: "d1-land",
        dayNumber: 1,
        date: "2026-05-16",
        time: "06:50",
        title: "Land at Madrid-Barajas T4",
        description: "Immigration is quick for US passports. Grab bags and head to the taxi rank.",
        tip: "Flat-rate taxi from T4 to central Madrid is €33.",
        location: { name: "Madrid-Barajas Airport T4", query: "Madrid Barajas Airport Terminal 4", lat: 40.4719, lng: -3.5626 },
        type: "travel",
        highlight: true,
        durationMinutes: 60,
      },
      {
        id: "d1-checkin",
        dayNumber: 1,
        date: "2026-05-16",
        time: "08:00",
        title: "Check in at URSO Hotel & Spa",
        description: "Boutique hotel in Chamberí in a restored 1920s palace. Request early check-in — they're great about it.",
        tip: "If the room isn't ready, they'll store luggage and you can use the spa.",
        location: { name: "URSO Hotel & Spa", address: "Calle de Mejía Lequerica, 8, 28004 Madrid", lat: 40.4264, lng: -3.6987 },
        type: "hotel",
        durationMinutes: 60,
        confirmation: "9086280313578",
      },
      {
        id: "d1-breakfast",
        dayNumber: 1,
        date: "2026-05-16",
        time: "09:30",
        title: "Breakfast",
        description: "URSO has a beautiful courtyard breakfast. Or walk to Tomá Café (Calle de la Palma 49) for specialty coffee and pastries.",
        location: { name: "Tomá Café", address: "Calle de la Palma, 49, Madrid", lat: 40.4243, lng: -3.7038 },
        type: "dining",
        durationMinutes: 60,
      },
      {
        id: "d1-malasana",
        dayNumber: 1,
        date: "2026-05-16",
        time: "10:30",
        title: "Explore Malasaña & Chueca",
        description: "Madrid's most vibrant neighborhoods. Independent shops, street art, café culture. Walk down to Gran Vía and through Plaza de Cibeles.",
        location: { name: "Malasaña", query: "Malasaña Madrid", lat: 40.4260, lng: -3.7045 },
        type: "activity",
        durationMinutes: 120,
      },
      {
        id: "d1-lunch",
        dayNumber: 1,
        date: "2026-05-16",
        time: "13:00",
        title: "Lunch at Mercado de San Miguel",
        description: "Gourmet market near Plaza Mayor. Graze on Manchego, Ibérico ham, croquetas, and a glass of Verdejo.",
        tip: "Arrive before 1:30 PM to beat the lunch rush.",
        location: { name: "Mercado de San Miguel", address: "Plaza de San Miguel, s/n, 28005 Madrid", lat: 40.4153, lng: -3.7089 },
        type: "dining",
        highlight: true,
        durationMinutes: 90,
      },
      {
        id: "d1-retiro",
        dayNumber: 1,
        date: "2026-05-16",
        time: "15:00",
        title: "Retiro Park & Prado Area",
        description: "Rent a rowboat on the lake, see the Crystal Palace. If you've got energy, the Prado is right there.",
        location: { name: "Retiro Park", query: "Parque del Retiro Madrid", lat: 40.4153, lng: -3.6845 },
        type: "activity",
        durationMinutes: 120,
      },
      {
        id: "d1-siesta",
        dayNumber: 1,
        date: "2026-05-16",
        time: "17:00",
        title: "Siesta / Spa",
        description: "You've been up since you landed. Head back, nap, use the thermal spa circuit. Recharge.",
        location: { name: "URSO Hotel & Spa", query: "URSO Hotel Spa Madrid" },
        type: "free",
        durationMinutes: 90,
      },
      {
        id: "d1-venencia",
        dayNumber: 1,
        date: "2026-05-16",
        time: "20:30",
        title: "Vermut at La Venencia",
        description: "Legendary sherry bar in Huertas that hasn't changed since the 1920s. No photos allowed. Fino, manzanilla, and oloroso from the barrel.",
        tip: "Cash only. Order a fino with olives.",
        location: { name: "La Venencia", address: "Calle de Echegaray, 7, 28014 Madrid", lat: 40.4158, lng: -3.6987 },
        type: "wine",
        durationMinutes: 60,
      },
      {
        id: "d1-tapas",
        dayNumber: 1,
        date: "2026-05-16",
        time: "21:30",
        title: "Tapas crawl in La Latina",
        description: "Calle Cava Baja is Madrid's best tapas street. Hit Juana La Loca (famous tortilla pintxo), Casa Lucas, and Txirimiri (Basque pintxos). Two or three stops with wine at each.",
        location: { name: "Calle Cava Baja", query: "Calle Cava Baja Madrid La Latina", lat: 40.4121, lng: -3.7102 },
        type: "dining",
        highlight: true,
        durationMinutes: 120,
      },
    ],
  },

  // ===== DAY 2 — Sun May 17 — Madrid → Seville + Football =====
  {
    dayNumber: 2,
    date: "2026-05-17",
    weekday: "Sunday",
    title: "Madrid → Seville",
    city: "Seville",
    emoji: "⚽",
    summary: "Relaxed Madrid morning, afternoon train to Seville, tapas, and Sevilla FC vs Real Madrid at 8:30 PM. Tony's birthday!",
    events: [
      {
        id: "d2-breakfast",
        dayNumber: 2,
        date: "2026-05-17",
        time: "09:00",
        title: "Breakfast at URSO",
        description: "Sleep in — no rush today. Tostada con tomate and strong café con leche.",
        location: { name: "URSO Hotel & Spa", query: "URSO Hotel Spa Madrid" },
        type: "dining",
        durationMinutes: 60,
      },
      {
        id: "d2-morning",
        dayNumber: 2,
        date: "2026-05-17",
        time: "10:00",
        title: "Madrid morning",
        description: "Bonus time in Madrid. Stroll Retiro Park, rent a rowboat, or do a quick Prado visit. Or just wander Chamberí with a coffee.",
        location: { name: "Retiro Park", query: "Parque del Retiro Madrid" },
        type: "activity",
        durationMinutes: 75,
      },
      {
        id: "d2-checkout",
        dayNumber: 2,
        date: "2026-05-17",
        time: "11:15",
        title: "Check out & taxi to Atocha",
        description: "Madrid-Puerta de Atocha-Almudena Grandes. The station has a famous indoor tropical garden. Arrive 20 min early.",
        location: { name: "Atocha Station", address: "Pl. del Emperador Carlos V, s/n, 28012 Madrid", lat: 40.4065, lng: -3.6930 },
        type: "travel",
        durationMinutes: 45,
      },
      {
        id: "d2-ave",
        dayNumber: 2,
        date: "2026-05-17",
        time: "12:00",
        title: "AVE Train → Seville",
        description: "High-speed rail to Sevilla-Santa Justa. Comfortable seats, WiFi, café car. Arrives 2:39 PM.",
        tip: "Locator: Z2T9RT",
        location: { name: "Atocha Station", query: "Atocha Station Madrid" },
        type: "travel",
        highlight: true,
        durationMinutes: 159,
        confirmation: "Z2T9RT",
      },
      {
        id: "d2-arrive-seville",
        dayNumber: 2,
        date: "2026-05-17",
        time: "14:39",
        title: "Arrive Sevilla-Santa Justa",
        description: "Quick taxi to your hotel. The station is ~15 minutes from the historic center.",
        location: { name: "Sevilla-Santa Justa", address: "Av. Kansas City, s/n, 41007 Sevilla", lat: 37.3919, lng: -5.9764 },
        type: "travel",
        durationMinutes: 30,
      },
      {
        id: "d2-hotel",
        dayNumber: 2,
        date: "2026-05-17",
        time: "15:15",
        title: "Check in at Hotel Colón Gran Meliá",
        description: "Five-star on Plaza Nueva, overlooking the cathedral. Amex FHR perks: $300 credit, daily breakfast, room upgrade, late checkout.",
        location: { name: "Hotel Colón Gran Meliá", address: "Canalejas, 1, 41001 Sevilla", lat: 37.3886, lng: -5.9953 },
        type: "hotel",
        durationMinutes: 45,
        confirmation: "9086785389099",
      },
      {
        id: "d2-lunch",
        dayNumber: 2,
        date: "2026-05-17",
        time: "16:00",
        title: "Late lunch: Bodega Santa Cruz",
        description: "Beloved no-frills tapas bar. Montaditos, fried fish, cheap fino sherry. Perfect pre-match fuel.",
        location: { name: "Bodega Santa Cruz", address: "Calle Rodrigo Caro, 1, 41004 Sevilla", lat: 37.3853, lng: -5.9912 },
        type: "dining",
        durationMinutes: 60,
      },
      {
        id: "d2-explore",
        dayNumber: 2,
        date: "2026-05-17",
        time: "17:30",
        title: "Explore the neighborhood",
        description: "Walk around Plaza Nueva, peek at the Cathedral from outside, stroll along the Guadalquivir river.",
        location: { name: "Plaza Nueva Seville", query: "Plaza Nueva Sevilla" },
        type: "activity",
        durationMinutes: 90,
      },
      {
        id: "d2-split",
        dayNumber: 2,
        date: "2026-05-17",
        time: "19:00",
        title: "Group splits up",
        description: "Charles & Tony head to the stadium. Carly & Ang stay for dinner at the hotel.",
        type: "activity",
        durationMinutes: 30,
      },
      {
        id: "d2-girls-dinner",
        dayNumber: 2,
        date: "2026-05-17",
        time: "19:00",
        title: "🍽️ Carly & Ang: Dinner at Colón Gran Meliá",
        description: "Use the FHR $300 property credit — El Burladero for Andalusian tapas or La Abacería. Rooftop plunge pool after.",
        location: { name: "Hotel Colón Gran Meliá", query: "Hotel Colon Gran Melia Seville" },
        type: "dining",
        splitGroup: "girls",
        durationMinutes: 120,
      },
      {
        id: "d2-lounge",
        dayNumber: 2,
        date: "2026-05-17",
        time: "19:30",
        title: "⚽ Charles & Tony: Lounge access",
        description: "1 hour of lounge access before kickoff. Drinks, food, soak up the pre-match buzz.",
        location: { name: "Estadio Sánchez-Pizjuán", address: "C. de Sevilla FC, s/n, 41005 Sevilla", lat: 37.3840, lng: -5.9706 },
        type: "sport",
        splitGroup: "guys",
        durationMinutes: 60,
      },
      {
        id: "d2-match",
        dayNumber: 2,
        date: "2026-05-17",
        time: "20:30",
        title: "⚽ Sevilla FC vs Real Madrid",
        description: "La Liga at the 43,000-seat Sánchez-Pizjuán. Premium fixture, electric atmosphere.",
        tip: "Tickets booked! Expect to be out by ~10:30 PM.",
        location: { name: "Estadio Sánchez-Pizjuán", query: "Estadio Sanchez Pizjuan Sevilla" },
        type: "sport",
        highlight: true,
        splitGroup: "guys",
        durationMinutes: 120,
      },
      {
        id: "d2-postmatch",
        dayNumber: 2,
        date: "2026-05-17",
        time: "22:30",
        title: "Post-match: El Rinconcillo",
        description: "Seville's oldest bar (est. 1670). They chalk your tab on the counter. Carrillada (pork cheeks), espinacas con garbanzos.",
        location: { name: "El Rinconcillo", address: "C. Gerona, 40, 41003 Sevilla", lat: 37.3936, lng: -5.9929 },
        type: "dining",
        splitGroup: "guys",
        durationMinutes: 90,
      },
    ],
  },

  // ===== DAY 3 — Mon May 18 — Sherry Triangle + Cádiz =====
  {
    dayNumber: 3,
    date: "2026-05-18",
    weekday: "Monday",
    title: "Sherry & Cádiz Beach",
    city: "Jerez / Cádiz",
    emoji: "🍷",
    summary: "Sherry tasting in Jerez, then a long beach afternoon in Cádiz with sunset drinks over the Atlantic.",
    events: [
      {
        id: "d3-breakfast",
        dayNumber: 3,
        date: "2026-05-18",
        time: "08:30",
        title: "Breakfast at the hotel",
        description: "FHR complimentary breakfast: fresh OJ, Ibérico ham, local pastries, café con leche.",
        location: { name: "Hotel Colón Gran Meliá", query: "Hotel Colon Gran Melia Seville" },
        type: "dining",
        durationMinutes: 60,
      },
      {
        id: "d3-drive-jerez",
        dayNumber: 3,
        date: "2026-05-18",
        time: "09:30",
        title: "Drive to Jerez (~1 hr)",
        description: "Rent a car for the day (~€40) or book a guided tour through La Belle Seville / Viator.",
        location: { name: "Jerez de la Frontera", query: "Jerez de la Frontera Spain" },
        type: "travel",
        durationMinutes: 60,
      },
      {
        id: "d3-lustau",
        dayNumber: 3,
        date: "2026-05-18",
        time: "10:30",
        title: "Bodegas Lustau",
        description: "One of Jerez's most respected sherry houses. Tour the solera system with tastings of fino, amontillado, oloroso, and PX.",
        tip: "Book at lustau.es. ~€15-25/person.",
        location: { name: "Bodegas Lustau", address: "C. Arcos, 53, 11402 Jerez de la Frontera", lat: 36.6833, lng: -6.1378 },
        type: "wine",
        highlight: true,
        durationMinutes: 90,
      },
      {
        id: "d3-juanito",
        dayNumber: 3,
        date: "2026-05-18",
        time: "12:15",
        title: "Lunch: Bar Juanito, Jerez",
        description: "Legendary tapas bar. Famous alcachofas (artichokes) and chicharrones. Fino sherry from the barrel.",
        location: { name: "Bar Juanito", address: "C. Pescadería Vieja, 8, 11403 Jerez de la Frontera", lat: 36.6855, lng: -6.1370 },
        type: "dining",
        durationMinutes: 60,
      },
      {
        id: "d3-drive-cadiz",
        dayNumber: 3,
        date: "2026-05-18",
        time: "13:15",
        title: "Drive to Cádiz (30 min)",
        description: "Europe's oldest continuously inhabited city. The coastal drive is gorgeous.",
        location: { name: "Cádiz", query: "Cadiz Spain" },
        type: "travel",
        durationMinutes: 30,
      },
      {
        id: "d3-beach",
        dayNumber: 3,
        date: "2026-05-18",
        time: "14:00",
        title: "Playa de la Caleta — Beach Afternoon",
        description: "Golden sand flanked by two castles. This is the Bond film beach from Die Another Day. Water in May is refreshing (~67°F).",
        tip: "No lounger rentals — bring towels from the hotel. Showers on the beach.",
        location: { name: "Playa de la Caleta", query: "Playa de la Caleta Cadiz", lat: 36.5290, lng: -6.3090 },
        type: "activity",
        highlight: true,
        durationMinutes: 150,
      },
      {
        id: "d3-oldtown",
        dayNumber: 3,
        date: "2026-05-18",
        time: "16:30",
        title: "Wander Old Town Cádiz",
        description: "Plaza de las Flores, the seafront promenade along Campo del Sur, Cádiz Cathedral. Late afternoon light is golden.",
        location: { name: "Old Town Cádiz", query: "Casco Antiguo Cadiz", lat: 36.5298, lng: -6.2950 },
        type: "activity",
        durationMinutes: 90,
      },
      {
        id: "d3-clandestina",
        dayNumber: 3,
        date: "2026-05-18",
        time: "18:00",
        title: "Sunset drinks: La Clandestina",
        description: "Rooftop bar with views over the Atlantic. Cocktails or local white wine while the sun drops into the ocean.",
        location: { name: "La Clandestina", query: "La Clandestina Cadiz rooftop", lat: 36.5310, lng: -6.2975 },
        type: "wine",
        durationMinutes: 90,
      },
      {
        id: "d3-drive-back",
        dayNumber: 3,
        date: "2026-05-18",
        time: "19:30",
        title: "Drive back to Seville (~1 hr 15 min)",
        description: "Return the rental car at the hotel or keep overnight. Designate a driver or book a car service — it's been a full day of tastings.",
        tip: "Spain has a strict 0.5 BAC limit. Consider booking a driver through the hotel or a local car service for this leg.",
        type: "travel",
        durationMinutes: 75,
      },
      {
        id: "d3-eslava",
        dayNumber: 3,
        date: "2026-05-18",
        time: "21:30",
        title: "Dinner: Eslava",
        description: "One of Seville's most acclaimed tapas restaurants in San Lorenzo. The slow-cooked egg with truffle and mushroom is legendary.",
        tip: "No reservations for the bar. Arrive at 9 PM to snag a spot.",
        location: { name: "Eslava", address: "C. Eslava, 3, 41002 Sevilla", lat: 37.3932, lng: -6.0013 },
        type: "dining",
        highlight: true,
        durationMinutes: 90,
      },
    ],
  },

  // ===== DAY 4 — Tue May 19 — Seville Culture =====
  {
    dayNumber: 4,
    date: "2026-05-19",
    weekday: "Tuesday",
    title: "Seville: Culture & Tapas",
    city: "Seville",
    emoji: "🏛️",
    summary: "Alcázar, the Cathedral, crossing into Triana, and a vermut-to-flamenco evening.",
    events: [
      {
        id: "d4-breakfast",
        dayNumber: 4,
        date: "2026-05-19",
        time: "09:00",
        title: "Breakfast at the hotel",
        description: "Leisurely start. Use that FHR credit.",
        location: { name: "Hotel Colón Gran Meliá", query: "Hotel Colon Gran Melia Seville" },
        type: "dining",
        durationMinutes: 60,
      },
      {
        id: "d4-alcazar",
        dayNumber: 4,
        date: "2026-05-19",
        time: "10:00",
        title: "Real Alcázar of Seville",
        description: "Breathtaking Mudéjar royal palace — lush gardens, Game of Thrones filming locations. Give yourself 2 hours.",
        tip: "The upper royal apartments tour (€6 extra) is worth it for smaller crowds.",
        location: { name: "Real Alcázar", address: "Patio de Banderas, s/n, 41004 Sevilla", lat: 37.3831, lng: -5.9913 },
        type: "culture",
        highlight: true,
        durationMinutes: 120,
      },
      {
        id: "d4-cathedral",
        dayNumber: 4,
        date: "2026-05-19",
        time: "12:00",
        title: "Seville Cathedral & Giralda Tower",
        description: "World's largest Gothic cathedral. Climb the Giralda (originally a minaret) for panoramic views. It's a ramp, not stairs.",
        location: { name: "Seville Cathedral", address: "Av. de la Constitución, s/n, 41004 Sevilla", lat: 37.3861, lng: -5.9929 },
        type: "culture",
        durationMinutes: 90,
      },
      {
        id: "d4-lunch",
        dayNumber: 4,
        date: "2026-05-19",
        time: "13:30",
        title: "Lunch: La Azotea",
        description: "Modern Andalusian cuisine. Salmorejo, atún rojo (red tuna). Pair with Manzanilla sherry or Verdejo white.",
        location: { name: "La Azotea", query: "La Azotea Sevilla", lat: 37.3893, lng: -5.9975 },
        type: "dining",
        durationMinutes: 90,
      },
      {
        id: "d4-triana",
        dayNumber: 4,
        date: "2026-05-19",
        time: "15:00",
        title: "Wander Triana",
        description: "Cross the Guadalquivir to Seville's historic ceramics and flamenco neighborhood. Browse Triana Market.",
        location: { name: "Triana", query: "Triana Sevilla", lat: 37.3828, lng: -6.0037 },
        type: "activity",
        durationMinutes: 120,
      },
      {
        id: "d4-pool",
        dayNumber: 4,
        date: "2026-05-19",
        time: "17:00",
        title: "Pool time at the hotel",
        description: "Rooftop plunge pool at the Colón Gran Meliá. May in Seville is ~80°F — perfect for an afternoon dip.",
        location: { name: "Hotel Colón Gran Meliá", query: "Hotel Colon Gran Melia Seville" },
        type: "free",
        durationMinutes: 120,
      },
      {
        id: "d4-vermut",
        dayNumber: 4,
        date: "2026-05-19",
        time: "19:00",
        title: "Vermut at Antiguo Bar Abadía",
        description: "A neighborhood vermutería in Santa Cruz. House-made vermouth on tap, marinated olives, anchovies.",
        location: { name: "Antiguo Bar Abadía", query: "Antiguo Bar Abadia Sevilla", lat: 37.3867, lng: -5.9886 },
        type: "wine",
        durationMinutes: 90,
      },
      {
        id: "d4-flamenco",
        dayNumber: 4,
        date: "2026-05-19",
        time: "20:30",
        title: "Flamenco (optional)",
        description: "La Carbonería is free in an old coal yard. Or book Casa de la Memoria for an intimate seated show (~€22).",
        location: { name: "La Carbonería", address: "C. Levíes, 18, 41004 Sevilla", lat: 37.3843, lng: -5.9871 },
        type: "culture",
        durationMinutes: 60,
      },
      {
        id: "d4-dinner",
        dayNumber: 4,
        date: "2026-05-19",
        time: "21:30",
        title: "Dinner: Casa Robles",
        description: "Elegant but unpretentious. Excellent seafood, Ibérico pork, and a deep wine list. A proper sit-down for your last Seville night.",
        location: { name: "Casa Robles", address: "C. Álvarez Quintero, 58, 41004 Sevilla", lat: 37.3878, lng: -5.9936 },
        type: "dining",
        highlight: true,
        durationMinutes: 120,
      },
    ],
  },

  // ===== DAY 5 — Wed May 20 — Drive Seville → Madrid =====
  {
    dayNumber: 5,
    date: "2026-05-20",
    weekday: "Wednesday",
    title: "Drive to Madrid via Wine Country",
    city: "Córdoba / Madrid",
    emoji: "🚗",
    summary: "Road trip through the Spanish heartland — Córdoba's Mezquita, La Mancha wine tastings, and Don Quixote's windmill country.",
    events: [
      {
        id: "d5-checkout",
        dayNumber: 5,
        date: "2026-05-20",
        time: "08:30",
        title: "Breakfast & check out",
        description: "Use remaining FHR credit at breakfast.",
        location: { name: "Hotel Colón Gran Meliá", query: "Hotel Colon Gran Melia Seville" },
        type: "dining",
        durationMinutes: 30,
      },
      {
        id: "d5-car",
        dayNumber: 5,
        date: "2026-05-20",
        time: "09:00",
        title: "Pick up rental car",
        description: "Santa Justa station or hotel area. Mid-size or SUV through SIXT or Europcar. One-way to Madrid (~€60-80).",
        location: { name: "Sevilla-Santa Justa", query: "Sevilla Santa Justa car rental" },
        type: "travel",
        durationMinutes: 30,
      },
      {
        id: "d5-mezquita",
        dayNumber: 5,
        date: "2026-05-20",
        time: "11:00",
        title: "Córdoba: Mezquita-Cathedral",
        description: "~1.5 hour drive from Seville. The famous mosque-cathedral with its forest of red-and-white striped arches — one of Spain's most iconic buildings.",
        location: { name: "Mezquita-Catedral de Córdoba", address: "C. Cardenal Herrero, 1, 14003 Córdoba", lat: 37.8789, lng: -4.7794 },
        type: "culture",
        highlight: true,
        durationMinutes: 90,
      },
      {
        id: "d5-drive-mancha",
        dayNumber: 5,
        date: "2026-05-20",
        time: "12:30",
        title: "Drive into La Mancha",
        description: "North on the A-4 through rolling plains. Windmills, olive groves, and vineyards to the horizon.",
        type: "travel",
        durationMinutes: 60,
      },
      {
        id: "d5-wine",
        dayNumber: 5,
        date: "2026-05-20",
        time: "13:30",
        title: "Wine tasting in Valdepeñas",
        description: "Stop at Bodegas Navarro López or Bodegas Real for Tempranillo (called Cencibel here) and Airén whites. Pair with Manchego cheese.",
        tip: "Tastings are often free or €5-10.",
        location: { name: "Valdepeñas", query: "Valdepeñas wine bodegas Spain", lat: 38.7622, lng: -3.3843 },
        type: "wine",
        durationMinutes: 60,
      },
      {
        id: "d5-lunch",
        dayNumber: 5,
        date: "2026-05-20",
        time: "15:00",
        title: "Lunch at a roadside venta",
        description: "Hearty Manchegan cuisine: migas (fried breadcrumbs with chorizo), pisto manchego, local wine. Don Quixote country.",
        type: "dining",
        durationMinutes: 60,
      },
      {
        id: "d5-drive-madrid",
        dayNumber: 5,
        date: "2026-05-20",
        time: "16:30",
        title: "Continue to Madrid (~2 hrs)",
        description: "Straight shot up the A-4.",
        type: "travel",
        durationMinutes: 120,
      },
      {
        id: "d5-hotel",
        dayNumber: 5,
        date: "2026-05-20",
        time: "18:30",
        title: "Check into Gran Hotel Inglés",
        description: "Madrid's #1 rated hotel on TripAdvisor, in the Barrio de las Letras. Drop the car at a nearby rental return.",
        location: { name: "Gran Hotel Inglés", address: "Calle de Echegaray, 8, 28014 Madrid", lat: 40.4155, lng: -3.6985 },
        type: "hotel",
        durationMinutes: 90,
        confirmation: "9100117664541",
      },
      {
        id: "d5-dinner",
        dayNumber: 5,
        date: "2026-05-20",
        time: "21:00",
        title: "Dinner: Sala de Despiece",
        description: "Buzzy modern tapas in Malasaña. Dishes on butcher paper, menu reads like a meat-cut chart. Creative, delicious, very Madrid.",
        location: { name: "Sala de Despiece", address: "C. de Ponzano, 11, 28010 Madrid", lat: 40.4337, lng: -3.6971 },
        type: "dining",
        highlight: true,
        durationMinutes: 90,
      },
    ],
  },

  // ===== DAY 6 — Thu May 21 — Ribera del Duero + DSTAgE =====
  {
    dayNumber: 6,
    date: "2026-05-21",
    weekday: "Thursday",
    title: "Ribera del Duero + DSTAgE",
    city: "Ribera del Duero / Madrid",
    emoji: "🍇",
    summary: "Day trip to Spain's great Tempranillo region — wineries, a castle, roast lamb — then DSTAgE for dinner with Tony & Ang.",
    events: [
      {
        id: "d6-breakfast",
        dayNumber: 6,
        date: "2026-05-21",
        time: "08:00",
        title: "Early breakfast at Gran Hotel Inglés",
        description: "FHR complimentary breakfast. Quick start for the drive north.",
        location: { name: "Gran Hotel Inglés", query: "Gran Hotel Ingles Madrid" },
        type: "dining",
        durationMinutes: 30,
      },
      {
        id: "d6-drive",
        dayNumber: 6,
        date: "2026-05-21",
        time: "08:30",
        title: "Drive to Ribera del Duero (~2 hrs)",
        description: "North on the A-1 toward Peñafiel. The Duero River valley landscape is beautiful.",
        type: "travel",
        durationMinutes: 120,
      },
      {
        id: "d6-protos",
        dayNumber: 6,
        date: "2026-05-21",
        time: "10:30",
        title: "Bodegas Protos, Peñafiel",
        description: "Iconic Ribera winery built into the hillside beneath Peñafiel Castle. Richard Rogers-designed facility. Taste Crianza, Reserva, and Gran Reserva Tempranillos.",
        tip: "Book at bodegasprotos.com. Tours from ~€15.",
        location: { name: "Bodegas Protos", address: "C. Bodegas Protos, 24, 47300 Peñafiel, Valladolid", lat: 41.5945, lng: -4.1099 },
        type: "wine",
        highlight: true,
        durationMinutes: 90,
      },
      {
        id: "d6-emiliomoro",
        dayNumber: 6,
        date: "2026-05-21",
        time: "12:30",
        title: "Bodegas Emilio Moro",
        description: "Family-run with beautiful grounds. Intimate winery experience, often includes food pairings.",
        location: { name: "Bodegas Emilio Moro", address: "Ctra. de Peñafiel a Valoria, s/n, 47315 Pesquera de Duero", lat: 41.6397, lng: -4.1566 },
        type: "wine",
        durationMinutes: 90,
      },
      {
        id: "d6-lunch",
        dayNumber: 6,
        date: "2026-05-21",
        time: "14:30",
        title: "Lunch: Aranda de Duero",
        description: "~45 min drive from Pesquera. Famous for lechazo — roast suckling lamb in wood-fired ovens. Try Asador Casa Florencio or Mesón de la Villa. Pair with a Ribera Reserva.",
        location: { name: "Aranda de Duero", query: "Asador Casa Florencio Aranda de Duero", lat: 41.6707, lng: -3.6889 },
        type: "dining",
        highlight: true,
        durationMinutes: 90,
      },
      {
        id: "d6-drive-back",
        dayNumber: 6,
        date: "2026-05-21",
        time: "16:00",
        title: "Drive back to Madrid (~2 hrs)",
        description: "Wine in the trunk, memories in the bank. Designate a driver — two winery tastings plus wine at lunch means someone needs to stay sharp.",
        tip: "If nobody's sober enough, book a driver through the hotel in advance or use BlaBlaCar/taxi from Aranda.",
        type: "travel",
        durationMinutes: 120,
      },
      {
        id: "d6-free",
        dayNumber: 6,
        date: "2026-05-21",
        time: "18:00",
        title: "Free time / Shopping",
        description: "Salamanca neighborhood for upscale shopping. Gifts: olive oil, saffron, cerámica tiles. Watch lovers: Rolex AD at C/ Serrano 52, plus Wempe and other luxury dealers on Calle Serrano & Ortega y Gasset.",
        location: { name: "Salamanca District", query: "Barrio Salamanca Madrid shopping" },
        type: "free",
        durationMinutes: 120,
      },
      {
        id: "d6-dstage",
        dayNumber: 6,
        date: "2026-05-21",
        time: "21:00",
        title: "🌟🌟 Dinner: DSTAgE (2 Michelin Stars)",
        description: "The big one. Chef Diego Guerrero's 16-course DTASTE menu blends Spanish, Mexican, and Japanese flavors. Open kitchen, unforgettable.",
        tip: "DTASTE menu €175/pp + optional wine pairing €90/pp. Booked!",
        location: { name: "DSTAgE", address: "Calle de Regueros, 8, 28004 Madrid", lat: 40.4259, lng: -3.6966 },
        type: "dining",
        highlight: true,
        durationMinutes: 150,
        confirmation: "BOOKED",
      },
      {
        id: "d6-nightcap",
        dayNumber: 6,
        date: "2026-05-21",
        time: "23:30",
        title: "Nightcap: Salmon Guru",
        description: "One of the World's 50 Best Bars, in Huertas. Creative cocktails in a vibrant, artsy space.",
        location: { name: "Salmon Guru", address: "C. de Echegaray, 21, 28014 Madrid", lat: 40.4150, lng: -3.6978 },
        type: "dining",
        durationMinutes: 90,
      },
    ],
  },

  // ===== DAY 7 — Fri May 22 — Fly Home =====
  {
    dayNumber: 7,
    date: "2026-05-22",
    weekday: "Friday",
    title: "Fly Home",
    city: "Madrid",
    emoji: "🏠",
    summary: "Last breakfast, then head to Barajas for your afternoon flight home.",
    events: [
      {
        id: "d7-wake",
        dayNumber: 7,
        date: "2026-05-22",
        time: "07:30",
        title: "Wake up & pack",
        description: "Flight at 12:20 PM. Barajas T4 recommends 3 hours early, but 2.5 is fine.",
        type: "activity",
        durationMinutes: 30,
      },
      {
        id: "d7-breakfast",
        dayNumber: 7,
        date: "2026-05-22",
        time: "08:00",
        title: "Final breakfast at Gran Hotel Inglés",
        description: "Savor that last café con leche.",
        location: { name: "Gran Hotel Inglés", query: "Gran Hotel Ingles Madrid" },
        type: "dining",
        durationMinutes: 60,
      },
      {
        id: "d7-checkout",
        dayNumber: 7,
        date: "2026-05-22",
        time: "09:00",
        title: "Check out & taxi to Barajas T4",
        description: "Flat-rate €33 from central Madrid. Or Metro from Sevilla station to T4.",
        location: { name: "Madrid-Barajas Airport T4", query: "Madrid Barajas Airport Terminal 4" },
        type: "travel",
        durationMinutes: 30,
      },
      {
        id: "d7-airport",
        dayNumber: 7,
        date: "2026-05-22",
        time: "09:30",
        title: "Airport — T4",
        description: "Security and passport control. Duty-free for last-minute wine, ham, or saffron.",
        location: { name: "Madrid-Barajas T4", query: "Madrid Barajas Airport Terminal 4" },
        type: "travel",
        durationMinutes: 150,
      },
      {
        id: "d7-flight",
        dayNumber: 7,
        date: "2026-05-22",
        time: "12:20",
        title: "IB 361 · MAD → IAD",
        description: "9h 10min nonstop on the A321neo. Arrive 3:30 PM at Dulles.",
        tip: "Check Iberia app for Premium Economy upgrade (~€150-200/pp). Confirmation: BR3EZO",
        location: { name: "Madrid-Barajas Airport T4", query: "Madrid Barajas Airport Terminal 4" },
        type: "travel",
        highlight: true,
        durationMinutes: 550,
        confirmation: "BR3EZO",
      },
    ],
  },
];
